// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PowerDiary.ChatHistory.Persistance;

#nullable disable

namespace PowerDiary.ChatHistory.Persistance.Migrations
{
    [DbContext(typeof(ChatAppDbContext))]
    partial class ChatAppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("PowerDiary.ChatHistory.Domain.Entities.ChatRoomEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("EventDetails")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EventId")
                        .HasColumnType("int");

                    b.Property<int?>("ReceiverId")
                        .HasColumnType("int");

                    b.Property<int>("SenderId")
                        .HasColumnType("int");

                    b.Property<DateTime>("TimeStamp")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("EventId");

                    b.HasIndex("ReceiverId");

                    b.HasIndex("SenderId");

                    b.ToTable("ChatRoomEvents", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EventDetails = "",
                            EventId = 1,
                            SenderId = 4,
                            TimeStamp = new DateTime(2022, 7, 3, 12, 48, 44, 260, DateTimeKind.Local).AddTicks(1009)
                        },
                        new
                        {
                            Id = 2,
                            EventDetails = "",
                            EventId = 1,
                            SenderId = 5,
                            TimeStamp = new DateTime(2022, 7, 3, 12, 48, 44, 260, DateTimeKind.Local).AddTicks(1047)
                        },
                        new
                        {
                            Id = 3,
                            EventDetails = "",
                            EventId = 1,
                            SenderId = 1,
                            TimeStamp = new DateTime(2022, 7, 3, 13, 48, 44, 260, DateTimeKind.Local).AddTicks(1049)
                        },
                        new
                        {
                            Id = 4,
                            EventDetails = "",
                            EventId = 1,
                            SenderId = 2,
                            TimeStamp = new DateTime(2022, 7, 3, 13, 48, 44, 260, DateTimeKind.Local).AddTicks(1051)
                        },
                        new
                        {
                            Id = 5,
                            EventDetails = "",
                            EventId = 1,
                            SenderId = 3,
                            TimeStamp = new DateTime(2022, 7, 3, 13, 48, 44, 260, DateTimeKind.Local).AddTicks(1053)
                        },
                        new
                        {
                            Id = 6,
                            EventDetails = "",
                            EventId = 1,
                            SenderId = 4,
                            TimeStamp = new DateTime(2022, 7, 3, 13, 50, 44, 260, DateTimeKind.Local).AddTicks(1056)
                        },
                        new
                        {
                            Id = 7,
                            EventDetails = "",
                            EventId = 1,
                            SenderId = 5,
                            TimeStamp = new DateTime(2022, 7, 3, 13, 50, 44, 260, DateTimeKind.Local).AddTicks(1058)
                        },
                        new
                        {
                            Id = 8,
                            EventDetails = "",
                            EventId = 1,
                            SenderId = 1,
                            TimeStamp = new DateTime(2022, 7, 3, 15, 48, 44, 260, DateTimeKind.Local).AddTicks(1060)
                        },
                        new
                        {
                            Id = 9,
                            EventDetails = "",
                            EventId = 2,
                            SenderId = 4,
                            TimeStamp = new DateTime(2022, 7, 3, 13, 48, 44, 260, DateTimeKind.Local).AddTicks(1062)
                        },
                        new
                        {
                            Id = 10,
                            EventDetails = "",
                            EventId = 2,
                            SenderId = 5,
                            TimeStamp = new DateTime(2022, 7, 3, 13, 48, 44, 260, DateTimeKind.Local).AddTicks(1065)
                        },
                        new
                        {
                            Id = 11,
                            EventDetails = "",
                            EventId = 2,
                            SenderId = 1,
                            TimeStamp = new DateTime(2022, 7, 3, 15, 18, 44, 260, DateTimeKind.Local).AddTicks(1067)
                        },
                        new
                        {
                            Id = 12,
                            EventDetails = "",
                            EventId = 2,
                            SenderId = 2,
                            TimeStamp = new DateTime(2022, 7, 3, 16, 48, 44, 260, DateTimeKind.Local).AddTicks(1069)
                        },
                        new
                        {
                            Id = 13,
                            EventDetails = "",
                            EventId = 2,
                            SenderId = 3,
                            TimeStamp = new DateTime(2022, 7, 3, 16, 48, 44, 260, DateTimeKind.Local).AddTicks(1071)
                        },
                        new
                        {
                            Id = 14,
                            EventDetails = "Hey - Vareesha how are you",
                            EventId = 3,
                            ReceiverId = 5,
                            SenderId = 4,
                            TimeStamp = new DateTime(2022, 7, 3, 13, 58, 44, 260, DateTimeKind.Local).AddTicks(1074)
                        },
                        new
                        {
                            Id = 15,
                            EventDetails = "Hey - Anam how are you",
                            EventId = 3,
                            ReceiverId = 5,
                            SenderId = 4,
                            TimeStamp = new DateTime(2022, 7, 3, 14, 0, 44, 260, DateTimeKind.Local).AddTicks(1077)
                        },
                        new
                        {
                            Id = 16,
                            EventDetails = "Hey - Harry how are you",
                            EventId = 3,
                            ReceiverId = 3,
                            SenderId = 1,
                            TimeStamp = new DateTime(2022, 7, 3, 14, 48, 44, 260, DateTimeKind.Local).AddTicks(1079)
                        },
                        new
                        {
                            Id = 17,
                            EventDetails = "Hey - Ali how are you",
                            EventId = 3,
                            ReceiverId = 1,
                            SenderId = 3,
                            TimeStamp = new DateTime(2022, 7, 3, 14, 53, 44, 260, DateTimeKind.Local).AddTicks(1081)
                        },
                        new
                        {
                            Id = 18,
                            EventDetails = "Hey - Ali how are you",
                            EventId = 3,
                            ReceiverId = 1,
                            SenderId = 2,
                            TimeStamp = new DateTime(2022, 7, 3, 14, 58, 44, 260, DateTimeKind.Local).AddTicks(1083)
                        },
                        new
                        {
                            Id = 19,
                            EventDetails = "Hey - Snow how are you",
                            EventId = 3,
                            ReceiverId = 2,
                            SenderId = 1,
                            TimeStamp = new DateTime(2022, 7, 3, 14, 0, 44, 260, DateTimeKind.Local).AddTicks(1086)
                        },
                        new
                        {
                            Id = 20,
                            EventDetails = "",
                            EventId = 4,
                            ReceiverId = 1,
                            SenderId = 4,
                            TimeStamp = new DateTime(2022, 7, 3, 13, 52, 44, 260, DateTimeKind.Local).AddTicks(1089)
                        },
                        new
                        {
                            Id = 21,
                            EventDetails = "",
                            EventId = 4,
                            ReceiverId = 1,
                            SenderId = 5,
                            TimeStamp = new DateTime(2022, 7, 3, 13, 52, 44, 260, DateTimeKind.Local).AddTicks(1092)
                        },
                        new
                        {
                            Id = 22,
                            EventDetails = "",
                            EventId = 4,
                            ReceiverId = 5,
                            SenderId = 4,
                            TimeStamp = new DateTime(2022, 7, 3, 14, 4, 44, 260, DateTimeKind.Local).AddTicks(1094)
                        },
                        new
                        {
                            Id = 23,
                            EventDetails = "",
                            EventId = 4,
                            ReceiverId = 4,
                            SenderId = 5,
                            TimeStamp = new DateTime(2022, 7, 3, 14, 6, 44, 260, DateTimeKind.Local).AddTicks(1096)
                        },
                        new
                        {
                            Id = 24,
                            EventDetails = "",
                            EventId = 4,
                            ReceiverId = 4,
                            SenderId = 2,
                            TimeStamp = new DateTime(2022, 7, 3, 14, 52, 44, 260, DateTimeKind.Local).AddTicks(1098)
                        },
                        new
                        {
                            Id = 25,
                            EventDetails = "",
                            EventId = 4,
                            ReceiverId = 5,
                            SenderId = 2,
                            TimeStamp = new DateTime(2022, 7, 3, 14, 52, 44, 260, DateTimeKind.Local).AddTicks(1101)
                        },
                        new
                        {
                            Id = 26,
                            EventDetails = "",
                            EventId = 4,
                            ReceiverId = 2,
                            SenderId = 4,
                            TimeStamp = new DateTime(2022, 7, 3, 14, 52, 44, 260, DateTimeKind.Local).AddTicks(1103)
                        },
                        new
                        {
                            Id = 27,
                            EventDetails = "",
                            EventId = 4,
                            ReceiverId = 2,
                            SenderId = 5,
                            TimeStamp = new DateTime(2022, 7, 3, 14, 52, 44, 260, DateTimeKind.Local).AddTicks(1105)
                        });
                });

            modelBuilder.Entity("PowerDiary.ChatHistory.Domain.Entities.Event", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Events", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Enter"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Leave"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Comment"
                        },
                        new
                        {
                            Id = 4,
                            Description = "High-Five"
                        });
                });

            modelBuilder.Entity("PowerDiary.ChatHistory.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Ali"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Snow"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Harry"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Anam"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Vareesha"
                        });
                });

            modelBuilder.Entity("PowerDiary.ChatHistory.Domain.Entities.ChatRoomEvent", b =>
                {
                    b.HasOne("PowerDiary.ChatHistory.Domain.Entities.Event", "Event")
                        .WithMany()
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PowerDiary.ChatHistory.Domain.Entities.User", "Receiver")
                        .WithMany()
                        .HasForeignKey("ReceiverId");

                    b.HasOne("PowerDiary.ChatHistory.Domain.Entities.User", "Sender")
                        .WithMany()
                        .HasForeignKey("SenderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");

                    b.Navigation("Receiver");

                    b.Navigation("Sender");
                });
#pragma warning restore 612, 618
        }
    }
}
